package day18;

import java.util.Scanner;

public class Handleexceptions {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner sc= new Scanner(System.in);
	       /*System.out.println("Enter number");
	        int num= sc.nextInt();
	        try {
	        	System.out.println(100/num);
	        }
	        catch(ArithmeticException e) {
	        	System.out.println("Invalid number. Please enter a number more than 0");
	        }
	        
	        
	        System.out.println("program is completed");
	        System.out.println("Program is exited");*/
	        
			/*int a[]= new int[5];
			System.out.println("Enter position: ");
			int pos= sc.nextInt();
			System.out.println("Enter value: ");
			int val= sc.nextInt();
			a[pos]=val;
			System.out.println(a[pos]);*/
	        String s= "12345";
	        int a=Integer.parseInt(s);
			//System.out.println(a);
			//System.out.println("String is now an integer ");
			
	}

}
